# Generated by Django 4.2 on 2023-05-13 19:31

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('dep', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100, null=True)),
                ('lastName', models.CharField(max_length=100, null=True)),
                ('university', models.CharField(max_length=100, null=True)),
                ('department', models.CharField(max_length=100, null=True)),
                ('studentCard', models.IntegerField(null=True)),
                ('studentSnum', models.IntegerField(null=True)),
                ('studenTel', models.CharField(max_length=100, null=True)),
                ('prepDeplome', models.CharField(max_length=100, null=True)),
                ('username', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prepDeplome', models.CharField(max_length=100, null=True)),
                ('duree', models.CharField(max_length=100, null=True)),
                ('strtDate', models.DateField(null=True)),
                ('endDate', models.DateField(null=True)),
                ('companyName', models.CharField(max_length=100, null=True)),
                ('companyAdrss', models.CharField(max_length=100, null=True)),
                ('workPlan', models.CharField(max_length=100, null=True)),
                ('gnrlDiscipline', models.IntegerField(null=True)),
                ('workAptitudes', models.IntegerField(null=True)),
                ('initiative', models.IntegerField(null=True)),
                ('innovationAbilities', models.IntegerField(null=True)),
                ('knowledgeAcquired', models.IntegerField(null=True)),
                ('fullMark', models.IntegerField(null=True)),
                ('Appreciation', models.CharField(max_length=100, null=True)),
                ('intern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intrn', to=settings.AUTH_USER_MODEL)),
                ('internMaster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mster', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InternshipApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approvedByMaster', models.BooleanField(blank=True, null=True)),
                ('approvedBySupervisor', models.BooleanField(blank=True, null=True)),
                ('MasterDefinitelyReject', models.BooleanField(blank=True, null=True)),
                ('SuprvDefinitelyReject', models.BooleanField(blank=True, null=True)),
                ('RejectionReason', models.CharField(max_length=100, null=True)),
                ('sprvisorName', models.CharField(blank=True, max_length=100, null=True)),
                ('sprvisorTel', models.IntegerField(null=True)),
                ('sprvisorFax', models.IntegerField(null=True)),
                ('sprvisorEmail', models.EmailField(max_length=254, null=True)),
                ('companyName', models.CharField(max_length=100, null=True)),
                ('companyAdrss', models.CharField(max_length=100, null=True)),
                ('studentName', models.CharField(blank=True, max_length=100, null=True)),
                ('studentdep', models.CharField(max_length=100, null=True)),
                ('studentCard', models.IntegerField(null=True)),
                ('studentSnum', models.IntegerField(null=True)),
                ('studenTel', models.CharField(max_length=100, null=True)),
                ('prepDeplome', models.CharField(max_length=100, null=True)),
                ('theme', models.CharField(max_length=100, null=True)),
                ('duree', models.CharField(max_length=100, null=True)),
                ('strtDate', models.DateField(null=True)),
                ('endDate', models.DateField(null=True)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='std', to=settings.AUTH_USER_MODEL)),
                ('internMaster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spv', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
