# Generated by Django 4.2 on 2023-05-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipapp',
            name='RejectionReason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Appreciation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='companyAdrss',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='companyName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='duree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='fullMark',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='gnrlDiscipline',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='initiative',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='innovationAbilities',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='knowledgeAcquired',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='prepDeplome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='strtDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='workAptitudes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='workPlan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
