# Generated by Django 4.2 on 2023-05-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_internshipapp_rejectionreason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='Appreciation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='gnrlDiscipline',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='initiative',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='innovationAbilities',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='knowledgeAcquired',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='workAptitudes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='workPlan',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
