# Generated by Django 4.2 on 2023-05-14 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_marks_appreciation_alter_marks_gnrldiscipline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prepDeplome', models.CharField(blank=True, max_length=100, null=True)),
                ('companyAdrss', models.CharField(blank=True, max_length=100, null=True)),
                ('strtDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('internshipDay', models.DateField(blank=True, null=True)),
                ('workingHours', models.DateField(blank=True, null=True)),
                ('observation', models.CharField(blank=True, max_length=100, null=True)),
                ('isPresent', models.BooleanField(blank=True, null=True)),
                ('intern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('internMaster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprvor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
