# Generated by Django 4.2 on 2023-05-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_attendence'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipapp',
            name='rated',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='workingHours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
