# Generated by Django 4.2 on 2023-06-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_internshipapp_rated_alter_attendence_workinghours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipapp',
            name='prepDeplome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='internshipapp',
            name='studenTel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='internshipapp',
            name='studentCard',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internshipapp',
            name='studentSnum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internshipapp',
            name='studentdep',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='studenTel',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
