# Generated by Django 4.2 on 2023-06-02 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_firstname_student_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
