# Generated by Django 4.2 on 2023-06-02 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_internshipapp_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipapp',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='std', to=settings.AUTH_USER_MODEL),
        ),
    ]
