# Generated by Django 4.2 on 2023-06-03 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_internoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipapp',
            name='StudentbirthDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internshipapp',
            name='StudentbirthPlace',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='StudentbirthDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='StudentbirthPlace',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='createdDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student',
            name='birthDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='birthPlace',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='Fax',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='Tel',
            field=models.IntegerField(null=True),
        ),
    ]
