# Generated by Django 4.2 on 2023-06-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_internshipapp_studentbirthdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internoffer',
            name='SprvisorFax',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='internoffer',
            name='SprvisorTel',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='internoffer',
            name='Sprvisoremail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='internoffer',
            name='Sprvisorfullname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internoffer',
            name='coverLetter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internoffer',
            name='duree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internshipapp',
            name='coverLetter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
