# Generated by Django 4.2 on 2023-06-04 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_admin_email_remove_admin_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipapp',
            name='depMaster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adm', to=settings.AUTH_USER_MODEL),
        ),
    ]
