# Generated by Django 4.2 on 2023-06-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_rename_user_student_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='approvedAccount',
            field=models.BooleanField(blank=True, default=False, max_length=100, null=True),
        ),
    ]
